version: "3.3"
services:
  web:
    image: :"imagemongo-web"
    container_name: web
    #build:      
    #  context: ..
    #  dockerfile: ./ImageMongoDb/Dockerfile
    #depends_on: [ mssql ]        
    ports:
      - "5024:80"
      - "5001:443"
  #mssql:
  #  image: "mcr.microsoft.com/mssql/server"
  #  container_name: mssql
  #  hostname: mssql
  #  environment:
  #    SA_PASSWORD: "Pass123!"
  #    ACCEPT_EULA: "Y"
  #  restart: unless-stopped    
  #  ports:
  #    # So we can access the database
  #    # From a tool like JetBrains Rider
  #    # Optional for this demo
  #    - "11433:1433" 
