#version: "3.3"
#services:
#  web:
#    image: :"imagemongo-web"
#    container_name: web
#    #build:      
#    #  context: ..
#    #  dockerfile: ./ImageMongoDb/Dockerfile
#    #depends_on: [ mssql ]        
#    ports:
#      - "5024:80"
#      - "5001:443"
#  #mssql:
#  #  image: "mcr.microsoft.com/mssql/server"
#  #  container_name: mssql
#  #  hostname: mssql
#  #  environment:
#  #    SA_PASSWORD: "Pass123!"
#  #    ACCEPT_EULA: "Y"
#  #  restart: unless-stopped    
#  #  ports:
#  #    # So we can access the database
#  #    # From a tool like JetBrains Rider
#  #    # Optional for this demo
#  #    - "11433:1433" 
version: "3.8"


services:
  mongoapi:
    build:
      context: .
      dockerfile: Dockerfile
    #image: Imagemongowebapi
    container_name: imagemongoweb-cont
    #networks:
    #  backend:
    #    ipv4_address: 172.60.0.10 ##No mandatory but must be in same bridge
     
    #environment: 
    #    DB_HOST: db ## same as the database service name
    #    DB_DATABASE: notesdb
    #    DB_PASSWORD: secret
    volumes: 
            - /imagemomngoweb
    ports: 
            - 5006:80
        
#networks:
#    default:
#        external:
#            name: custom-net
#networks:
#     custom-net:
#        external: true
#        name: custom-net
#networks:
#     backend:
#        external: true
#        name: custom-net