name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image1
      run: |
           dockername = $(my-image-name:$(date +%s))
           echo $dockername
           docker build . --file Dockerfile --tag $dockername
        
    - name: Artifact upload
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/dockername
   
